#version: '3.3'
#
#services:
#  #service 1: definition of mysql database
#  db:
#    platform: linux/x86_64
#    image: mysql:5.6
#    networks:
#      - school-system-mysql
#    container_name: mysqldb
#    environment:
#      - MYSQL_ROOT_PASSWORD=spring
#    ports:
#      - "3306:3306"
#    expose:
#      - "3306"
#    restart: always
##
##  #service 2: definition of phpMyAdmin
##  phpmyadmin:
##    image: phpmyadmin/phpmyadmin:latest
##    container_name: my-php-myadmin
##    ports:
##      - "8082:80"
##    restart: always
##
##    depends_on:
##      - db
##    environment:
##      SPRING_DATASOURCE_USERNAME: root
##      SPRING_DATASOURCE_PASSWORD: spring
##
##
##
##  #service 3: definition of your spring-boot app
#  schoolsystemservice:
#    image: school-system
#    container_name: school-system-app
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8084:8084"
#    networks:
#      - school-system-mysql
#    restart: always
#
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/property?createDatabaseIfNotExist=true
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: spring
#

version: "3.7"
services:
  schoolsystemservice:
    build: .
    restart: always
    ports:
      - 8084:8084